### ISSUE TITLE
How to build the web viewer?

### ISSUE THREAD

**Issue by RenieWell** [KeKsBoTer/web-splat#1]
Thanks for sharing the great works!

I have successfully ran the viewer.exe in windows, but failed in linux.  The problem is that the linux server don't have a GUI, and I got the following output:

> thread 'main' panicked at /data/c3dgs/web-splat/src/lib.rs:499:39:
called `Result::unwrap()` on an `Err` value: Os(OsError { line: 776, file: "/data/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor DISPLAY is set.") })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I know nothing about the rust, but it looks like the viewer can run in a web viwer.
Can you please kindly provide some detials of building the web viewer?

**Comment by KeKsBoTer** [comment]
You can build the web viewer by executing the `build_wasm.sh` file.
For this you need to install [wasm-bindgen-cli](https://rustwasm.github.io/wasm-bindgen/reference/cli.html) and add install the wasm target (e.g. with `rustup target add wasm32-unknown-unknown`).

This script creates the necessary files in the `public` folder. 
You can than open the `public/index.html` in your browser. 

Note that the files have to be provided via the URL. Example:
```
https://keksboter.github.io/web-splat/?file=./scenes/bicycle/point_cloud/iteration_35000/point_cloud.npz&scene=./scenes/bicycle/cameras.json
```

**Comment by RenieWell** [comment]
Thanks a lot!

**Comment by JonHe2002** [comment]
Hi,there are some problems I sincerely hope you to help me.

First,I installed _wasm-bindgen-cli_ and _wasm32-unknown-unknown_ in vscode but how to execute **build_wasm.sh**,
in WSL or any other ways and how to provide files via URL,could you refer me to some blogs?

Second,I successfully finished 'cargo build --release --bin viewer ' in WSL Ubuntu,
but after I have already checked the path of the two files, when I 'cargo run --release --bin viewer src\bin\point_cloud.ply src\bin\cameras.json' ,

it still reports:
thread 'main' panicked at src/bin/viewer.rs:53:44:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bash: aa12a154b52dbea/src/bin/point_cloud.ply: No such file or directory

![屏幕截图 2024-05-07 203734](https://github.com/KeKsBoTer/web-splat/assets/108330562/beb4a7f8-dce5-4ba4-affa-0c1f738e3ae0)
