### ISSUE TITLE
build viewer failed

### ISSUE THREAD

**Issue by yhccc** [KeKsBoTer/web-splat#2]
Thanks for your great works!
I get the following error when I run the command "cargo build --release --bin viewer ".
![image](https://github.com/KeKsBoTer/web-splat/assets/44393190/8ad450c9-702a-47c5-b9ea-2b2e80c1c4f2)
I'm not familiar with rust. Can you give me some advice?

**Comment by KeKsBoTer** [comment]
Thanks! 
I just pushed a fix to the master branch :)
