### ISSUE TITLE
Missings arguments in 'open_window' when compiling to targetArch "wasm32"

### ISSUE THREAD

**Issue by gejingze0131** [KeKsBoTer/web-splat#3]
Hi Simon, 
I've encountered an issue while attempting to compile the web-splat renderer into WebAssembly.  The following errors were encountered:

error[E0061]: this function takes 5 arguments but 3 arguments were supplied
   --> src/lib.rs:769:39
    |
769 |       wasm_bindgen_futures::spawn_local(open_window(
    |  _______________________________________^^^^^^^^^^^-
770 | |         pc_reader,
771 | |         scene_reader,
772 | |         RenderConfig { no_vsync: false,skybox:None },
773 | |     ));
    | |_____- two arguments of type `std::option::Option<PathBuf>` and `std::option::Option<PathBuf>` are missing
    |
note: function defined here
   --> src/lib.rs:554:14
    |
554 | pub async fn open_window<R: Read + Seek + Send + Sync + 'static>(
    |              ^^^^^^^^^^^
555 |     file: R,
    |     -------
556 |     scene_file: Option<R>,
    |     ---------------------
557 |     config: RenderConfig,
    |     --------------------
558 |     pointcloud_file_path: Option<PathBuf>,
    |     -------------------------------------
559 |     scene_file_path: Option<PathBuf>,
    |     --------------------------------
help: provide the arguments
    |
769 |     wasm_bindgen_futures::spawn_local(open_window(pc_reader, scene_reader, RenderConfig { no_vsync: false,skybox:None }, /* std::option::Option<PathBuf> */, /* std::option::Option<PathBuf> */));
    |

**Comment by KeKsBoTer** [comment]
I pushed a fix to the master branch
